version: '3.7'
services:
  myweb.com:
    #build: myweb.com
    image: penan9/pythontodo_myweb.com
    restart: always
    ports:
      - '5001:5001'
    environment:
      - DEBUG=0
    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - '80:80'
    networks:
      - flask_network

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
    flask_network:

volumes:
  postgres_data:
